package domain































































































}	return validStatuses[s]	}		"blocked":  true,		"inactive": true,		"active":   true,	validStatuses := map[string]bool{func isValidStatus(s string) bool {}	return validTypes[t]	}		"wholesale": true,		"retail":    true,		"b2c":       true,		"b2b":       true,	validTypes := map[string]bool{func isValidCustomerType(t string) bool {}	return c.CurrentBalance > 0	// This would need transaction data - placeholder logicfunc (c *Customer) IsOverdue() bool {// IsOverdue checks if customer has overdue payments}	return c.CurrentBalance+amount <= c.CreditLimit	}		return false	if c.Status != "active" {func (c *Customer) CanPurchase(amount float64) bool {// CanPurchase checks if customer can make a purchase}	return nil	}		return ErrInvalidInput("credit limit cannot be negative")	if c.CreditLimit < 0 {	}		return ErrInvalidInput("invalid status")	if c.Status != "" && !isValidStatus(c.Status) {	}		return ErrInvalidInput("invalid customer type")	if c.CustomerType != "" && !isValidCustomerType(c.CustomerType) {	}		return ErrInvalidInput("name is required")	if c.Name == "" {func (c *Customer) Validate() error {// Validate validates customer business rules}	Offset       int	Limit        int	SearchTerm   string	CustomerType string	Status       stringtype CustomerFilters struct {// CustomerFilters represents query filters for customers}	DeletionReason      string	DeletedBy           string	DeletedAt           *time.Time	UpdatedAt           time.Time	CreatedAt           time.Time	LoyaltyPoints       int	TotalPurchases      float64	LastTransactionDate *time.Time	Tags                []string	Notes               string	Status              string // active, inactive, blocked	InterestRate        float64	PaymentTermsDays    int	CurrentBalance      float64	CreditLimit         float64	KYCDocumentNumber   string	KYCDocumentType     string	AadhaarVerified     bool	CustomerType        string // b2b, b2c, retail, wholesale	GSTIN               string	BusinessName        string	PhotoURL            string	WhatsappNumber      string	AlternateContact    string	ContactNumber       string	Address             string	Email               string	Name                string	ID                  stringtype Customer struct {// Customer represents a customer entity with complete business fieldsimport "time"package domain