package httputil


















































































































}	return nil	}		return domain.ErrInvalidInput("invalid JSON body")	if err := json.NewDecoder(r.Body).Decode(v); err != nil {func DecodeJSON(r *http.Request, v interface{}) error {// DecodeJSON decodes JSON request body}	}		}			Message: "An internal error occurred",			Code:    "INTERNAL_ERROR",		return http.StatusInternalServerError, &ErrorData{		// Generic internal server error	default:		}			Message: err.Error(),			Code:    "MISSING_REASON",		return http.StatusBadRequest, &ErrorData{	case errors.Is(err, domain.ErrMissingReason):		}			Message: err.Error(),			Code:    "INVALID_ATTESTATION",		return http.StatusBadRequest, &ErrorData{	case errors.Is(err, domain.ErrInvalidAttestation):		}			Message: err.Error(),			Code:    "FORBIDDEN",		return http.StatusForbidden, &ErrorData{	case errors.Is(err, domain.ErrForbidden):		}			Message: err.Error(),			Code:    "UNAUTHORIZED",		return http.StatusUnauthorized, &ErrorData{	case errors.Is(err, domain.ErrUnauthorized):		}			Message: err.Error(),			Code:    "ALREADY_EXISTS",		return http.StatusConflict, &ErrorData{	case errors.Is(err, domain.ErrAlreadyExists):		}			Message: err.Error(),			Code:    "NOT_FOUND",		return http.StatusNotFound, &ErrorData{	case errors.Is(err, domain.ErrNotFound):	switch {	// Check for common domain errors	}		}			Message: businessErr.Message,			Code:    businessErr.Code,		return http.StatusUnprocessableEntity, &ErrorData{	if errors.As(err, &businessErr) {	var businessErr *domain.BusinessError	// Check for business errors	}		}			Field:   validationErr.Field,			Message: validationErr.Message,			Code:    "VALIDATION_ERROR",		return http.StatusBadRequest, &ErrorData{	if errors.As(err, &validationErr) {	var validationErr *domain.ValidationError	// Check for validation errorsfunc mapError(err error) (int, *ErrorData) {// mapError maps domain errors to HTTP status codes and error data}	})		Error:   errData,		Success: false,	json.NewEncoder(w).Encode(Response{	w.WriteHeader(statusCode)	w.Header().Set("Content-Type", "application/json")	statusCode, errData := mapError(err)func SendError(w http.ResponseWriter, err error) {// SendError sends an error JSON response}	})		Data:    data,		Success: statusCode < 400,	json.NewEncoder(w).Encode(Response{	w.WriteHeader(statusCode)	w.Header().Set("Content-Type", "application/json")func SendJSON(w http.ResponseWriter, statusCode int, data interface{}) {// SendJSON sends a JSON response}	Field   string `json:"field,omitempty"`	Message string `json:"message"`	Code    string `json:"code"`type ErrorData struct {// ErrorData represents error details in API response}	Error   *ErrorData  `json:"error,omitempty"`	Data    interface{} `json:"data,omitempty"`	Success bool        `json:"success"`type Response struct {// Response represents a standard API response)	"github.com/yourusername/vms/backend/internal/domain"	"net/http"	"errors"	"encoding/json"import (package httputil