package repository






































































































































































}	Update(ctx context.Context, schedule *domain.PaymentSchedule) error	// Update updates a payment schedule	List(ctx context.Context, customerID string) ([]*domain.PaymentSchedule, error)	// List retrieves payment schedules	GetByID(ctx context.Context, id string) (*domain.PaymentSchedule, error)	// GetByID retrieves a payment schedule by ID	Create(ctx context.Context, schedule *domain.PaymentSchedule) error	// Create creates a new payment scheduletype PaymentScheduleRepository interface {// PaymentScheduleRepository defines the interface for payment schedule data access}	Acknowledge(ctx context.Context, id, userID string) error	// Acknowledge marks alert as acknowledged	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes an expiry alert	Update(ctx context.Context, alert *domain.ExpiryAlert) error	// Update updates an expiry alert	List(ctx context.Context, acknowledged *bool) ([]*domain.ExpiryAlert, error)	// List retrieves expiry alerts	GetByID(ctx context.Context, id string) (*domain.ExpiryAlert, error)	// GetByID retrieves an expiry alert by ID	Create(ctx context.Context, alert *domain.ExpiryAlert) error	// Create creates a new expiry alerttype ExpiryAlertRepository interface {// ExpiryAlertRepository defines the interface for expiry alert data access}	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes a wastage log	Update(ctx context.Context, log *domain.WastageLog) error	// Update updates a wastage log	List(ctx context.Context) ([]*domain.WastageLog, error)	// List retrieves wastage logs	GetByID(ctx context.Context, id string) (*domain.WastageLog, error)	// GetByID retrieves a wastage log by ID	Create(ctx context.Context, log *domain.WastageLog) error	// Create creates a new wastage log entrytype WastageRepository interface {// WastageRepository defines the interface for wastage log data access}	GetBalance(ctx context.Context, customerID string) (int, error)	// GetBalance retrieves crate balance for a customer	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes a crate entry	Update(ctx context.Context, entry *domain.CrateEntry) error	// Update updates a crate entry	List(ctx context.Context, customerID string) ([]*domain.CrateEntry, error)	// List retrieves crate entries	GetByID(ctx context.Context, id string) (*domain.CrateEntry, error)	// GetByID retrieves a crate entry by ID	Create(ctx context.Context, entry *domain.CrateEntry) error	// Create creates a new crate entrytype CrateRepository interface {// CrateRepository defines the interface for crate ledger data access}	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes a sale item	Update(ctx context.Context, item *domain.SaleItem) error	// Update updates a sale item	GetByTransactionID(ctx context.Context, transactionID string) ([]*domain.SaleItem, error)	// GetByTransactionID retrieves sale items for a transaction	CreateBatch(ctx context.Context, items []*domain.SaleItem) error	// CreateBatch creates multiple sale itemstype SaleItemRepository interface {// SaleItemRepository defines the interface for sale item data access}	GenerateInvoiceNumber(ctx context.Context) (string, error)	// GenerateInvoiceNumber generates a unique invoice number	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes a transaction	Update(ctx context.Context, transaction *domain.Transaction) error	// Update updates an existing transaction	List(ctx context.Context, filters domain.TransactionFilters) ([]*domain.Transaction, error)	// List retrieves transactions with optional filters	GetByID(ctx context.Context, id string) (*domain.Transaction, error)	// GetByID retrieves a transaction by ID	Create(ctx context.Context, transaction *domain.Transaction) error	// Create creates a new transactiontype TransactionRepository interface {// TransactionRepository defines the interface for transaction data access}	DecrementQuantity(ctx context.Context, itemID string, amount float64) error	// DecrementQuantity decrements item quantity by amount	UpdateQuantity(ctx context.Context, itemID string, newQuantity float64) error	// UpdateQuantity updates item quantity	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes an inventory item	Update(ctx context.Context, item *domain.InventoryItem) error	// Update updates an existing inventory item	List(ctx context.Context, filters domain.InventoryFilters) ([]*domain.InventoryItem, error)	// List retrieves inventory items with optional filters	GetByID(ctx context.Context, id string) (*domain.InventoryItem, error)	// GetByID retrieves an inventory item by ID	Create(ctx context.Context, item *domain.InventoryItem) error	// Create creates a new inventory itemtype InventoryRepository interface {// InventoryRepository defines the interface for inventory data access}	GetBalance(ctx context.Context, customerID string) (float64, error)	// GetBalance retrieves customer's current balance	UpdateBalance(ctx context.Context, customerID string, newBalance float64) error	// UpdateBalance updates customer's current balance	SoftDelete(ctx context.Context, id, deletedBy, reason string) error	// SoftDelete soft deletes a customer	Update(ctx context.Context, customer *domain.Customer) error	// Update updates an existing customer	List(ctx context.Context, filters domain.CustomerFilters) ([]*domain.Customer, error)	// List retrieves customers with optional filters	GetByID(ctx context.Context, id string) (*domain.Customer, error)	// GetByID retrieves a customer by ID	Create(ctx context.Context, customer *domain.Customer) error	// Create creates a new customertype CustomerRepository interface {// CustomerRepository defines the interface for customer data access)	"github.com/yourusername/vms/backend/internal/domain"	"context"import (package repository